/**
 * data.js — EmojiDub
 * Banco de dados de emojis com personalidades e dicas de dublagem
 */

const EMOJI_DATA = [
  {
    e: '😂',
    name: 'Gargalhada',
    desc: 'Rir sem parar, histérico, não consegue parar',
    hint: 'Tente uma risada escandalosa e contagiante. Ex: "Hahahaha meu Deus não aguento!" ou apenas uma risada pura e incontrolável.',
    tags: ['risada', 'contagiante', 'explosivo'],
    defaultPitch: 1.4,
    defaultRate: 1.3,
  },
  {
    e: '😭',
    name: 'Choro Dramático',
    desc: 'Choro exagerado, teatral, muito dramático',
    hint: 'Tente um choro bem dramático e sofrido. Ex: "Aiiiii que tristeza... não aguento mais..." ou simplesmente chore com intensidade.',
    tags: ['triste', 'dramático', 'exagerado'],
    defaultPitch: 0.9,
    defaultRate: 0.85,
  },
  {
    e: '😡',
    name: 'Furiosa',
    desc: 'Raiva pura, bufando e resmungando',
    hint: 'Tente um resmungo irritado e bufante. Ex: "Não acredito! Que absurdo isso!" com muita raiva na voz.',
    tags: ['raiva', 'intenso', 'bufante'],
    defaultPitch: 0.85,
    defaultRate: 1.2,
  },
  {
    e: '😴',
    name: 'Sonâmbulo',
    desc: 'Bocejando, arrastado, quase dormindo',
    hint: 'Tente um bocejo longo e arrastado. Ex: "Ahmmm... tô dormindo... que sono..." bem devagarzinho e sem energia.',
    tags: ['sono', 'arrastado', 'bocejo'],
    defaultPitch: 0.8,
    defaultRate: 0.6,
  },
  {
    e: '🤩',
    name: 'Maravilhado',
    desc: 'Empolgação extrema, animadíssimo',
    hint: 'Tente empolgação máxima! Ex: "NOSSA QUE INCRÍVEL! Que coisa linda! Amei!!!" com muita energia e entusiasmo.',
    tags: ['animado', 'vibrante', 'empolgado'],
    defaultPitch: 1.5,
    defaultRate: 1.4,
  },
  {
    e: '🥺',
    name: 'Carente',
    desc: 'Voz pequena, fofa e suplicante',
    hint: 'Tente voz pequenininha e carente. Ex: "Por faaavorr... você consegue? Por favorzinhoo?" bem fininho e suplicante.',
    tags: ['fofo', 'suplicante', 'delicado'],
    defaultPitch: 1.3,
    defaultRate: 0.9,
  },
  {
    e: '😱',
    name: 'Apavorada',
    desc: 'Horror puro, chocado e assustado',
    hint: 'Tente um grito de susto contido. Ex: "Não! Que!? Meu Deus! Não acredito!" com voz horrorizada.',
    tags: ['assustado', 'chocado', 'intenso'],
    defaultPitch: 1.4,
    defaultRate: 1.3,
  },
  {
    e: '🤣',
    name: 'Histérica',
    desc: 'Rindo rolando no chão, completamente histérica',
    hint: 'Tente riso histérico incontrolável. Ex: "Ahahaha tô MORTA! Tô caindo! AHahahaha socorro!" perdendo o fôlego.',
    tags: ['histérico', 'caótico', 'rolando'],
    defaultPitch: 1.6,
    defaultRate: 1.5,
  },
  {
    e: '😏',
    name: 'Debochado',
    desc: 'Tom irônico, arrogante e debochado',
    hint: 'Tente um "hmm" irônico e lento. Ex: "Ah claro... com certeza... se você achar..." bem debochado e pausado.',
    tags: ['irônico', 'debochado', 'arrogante'],
    defaultPitch: 1.0,
    defaultRate: 0.85,
  },
  {
    e: '🥰',
    name: 'Apaixonada',
    desc: 'Derretendo de amor, completamente apaixonada',
    hint: 'Tente voz melosa e apaixonada. Ex: "Ai que amor... que coisa linda... te amo tanto..." com suspiros suaves.',
    tags: ['amoroso', 'suave', 'derretendo'],
    defaultPitch: 1.2,
    defaultRate: 0.85,
  },
  {
    e: '😤',
    name: 'Indignado',
    desc: 'Bufando de indignação, muito ofendido',
    hint: 'Tente um bufar indignado. Ex: "Humpf! Que descaso! Sério?! Que falta de respeito!" bufando forte entre as frases.',
    tags: ['indignado', 'bufante', 'ofendido'],
    defaultPitch: 0.9,
    defaultRate: 1.1,
  },
  {
    e: '🤔',
    name: 'Pensativo',
    desc: 'Hmm… pensando alto, reflexivo',
    hint: 'Tente pensar em voz alta devagar. Ex: "Hmm... interessante... deixa eu pensar... hm... sim..." bem pausado e reflexivo.',
    tags: ['reflexivo', 'pensativo', 'lento'],
    defaultPitch: 0.95,
    defaultRate: 0.8,
  },
  {
    e: '🎉',
    name: 'Festeiro',
    desc: 'Eufórico de festa, animadíssimo',
    hint: 'Tente grito de festa máximo! Ex: "VAMOS! É FESTA! Que animação! UHUU! YEAAH!" como se estivesse pulando de alegria.',
    tags: ['festeiro', 'eufórico', 'explosivo'],
    defaultPitch: 1.5,
    defaultRate: 1.4,
  },
  {
    e: '😎',
    name: 'Coolzão',
    desc: 'Confiante, cool, pausado e estiloso',
    hint: 'Tente falar super pausado e confiante. Ex: "Relaxa. Tô aqui. Pode contar comigo. Sempre foi assim." sem pressa alguma.',
    tags: ['cool', 'confiante', 'estiloso'],
    defaultPitch: 0.85,
    defaultRate: 0.8,
  },
  {
    e: '🤯',
    name: 'Mente Explodida',
    desc: 'Incrédulo, confuso, cabeça explodindo',
    hint: 'Tente incredulidade total. Ex: "MAS COMO?! Espera! Que!? Não entendo nada! Minha cabeça!" de forma caótica e confusa.',
    tags: ['caótico', 'incrédulo', 'confuso'],
    defaultPitch: 1.3,
    defaultRate: 1.3,
  },
  {
    e: '😫',
    name: 'Exausta',
    desc: 'Completamente esgotada, sem energia',
    hint: 'Tente esgotamento total. Ex: "Ai... não aguento mais... tô destruída... sem energia alguma..." bem lento e sem força.',
    tags: ['esgotado', 'sem energia', 'lento'],
    defaultPitch: 0.85,
    defaultRate: 0.65,
  },
  {
    e: '🤗',
    name: 'Calorosa',
    desc: 'Abraçando com a voz, acolhedora',
    hint: 'Tente voz calorosa e acolhedora. Ex: "Que bom te ver! Vem cá! Você é incrível, sabia? Te adoro muito!" com muito calor humano.',
    tags: ['caloroso', 'acolhedor', 'suave'],
    defaultPitch: 1.1,
    defaultRate: 0.95,
  },
  {
    e: '😬',
    name: 'Constrangido',
    desc: 'Awkward, constrangido, situação estranha',
    hint: 'Tente um riso nervoso e constrangido. Ex: "Heh... é... isso... que situação né... heheh..." completamente sem graça.',
    tags: ['awkward', 'nervoso', 'constrangido'],
    defaultPitch: 1.0,
    defaultRate: 1.0,
  },
  {
    e: '🥹',
    name: 'Emocionada',
    desc: 'Segurando o choro de tanto amor',
    hint: 'Tente voz embargada de emoção. Ex: "Não... que coisa mais linda... tô quase chorando... de verdade..." tremendo de emoção.',
    tags: ['emocionado', 'tocado', 'sensível'],
    defaultPitch: 1.1,
    defaultRate: 0.85,
  },
  {
    e: '😆',
    name: 'Alegre',
    desc: 'Feliz e risonho, sem parar de sorrir',
    hint: 'Tente voz animada e risonha. Ex: "Que delícia! Que dia incrível! Tô muito feliz hoje, sério!" com sorriso na voz.',
    tags: ['feliz', 'alegre', 'animado'],
    defaultPitch: 1.2,
    defaultRate: 1.1,
  },

  // ── ROSTOS ADICIONAIS ──────────────────────────────────
  {
    e: '😀',
    name: 'Radiante',
    desc: 'Sorriso enorme, felicidade pura',
    hint: 'Tente voz super animada e calorosa. Ex: "Que dia INCRÍVEL! Tô sorrindo de orelha a orelha!" bem aberto e feliz.',
    tags: ['feliz', 'radiante', 'aberto'],
    defaultPitch: 1.2,
    defaultRate: 1.05,
  },
  {
    e: '😃',
    name: 'Animadão',
    desc: 'Animado com olhos grandes, muito contente',
    hint: 'Tente empolgação contagiante. Ex: "Nossa, que bom! Adorei! Que novidade!" com voz bem viva e energética.',
    tags: ['animado', 'contente', 'energético'],
    defaultPitch: 1.25,
    defaultRate: 1.1,
  },
  {
    e: '😄',
    name: 'Eufórico',
    desc: 'Sorrindo com os olhos, eufórico',
    hint: 'Tente alegria genuína e contagiante. Ex: "Hahaha que coisa boa! Tô muito feliz com isso!" rindo junto.',
    tags: ['eufórico', 'genuíno', 'contagiante'],
    defaultPitch: 1.3,
    defaultRate: 1.15,
  },
  {
    e: '😁',
    name: 'Satisfeito',
    desc: 'Sorriso travesso com dentes, muito satisfeito',
    hint: 'Tente voz travessa e satisfeita. Ex: "Eheheh... deu certo! Sabia que ia dar! Tô muito satisfeito!" com orgulho.',
    tags: ['travesso', 'satisfeito', 'orgulhoso'],
    defaultPitch: 1.15,
    defaultRate: 1.0,
  },
  {
    e: '😅',
    name: 'Aliviado',
    desc: 'Rindo nervoso de alívio, ufa!',
    hint: 'Tente riso nervoso de alívio. Ex: "Heheh... que susto! Ainda bem que deu certo... ufa!" soltando o ar.',
    tags: ['aliviado', 'nervoso', 'ufa'],
    defaultPitch: 1.1,
    defaultRate: 1.05,
  },
  {
    e: '🙂',
    name: 'Tranquilo',
    desc: 'Sorriso sutil, tranquilo e neutro',
    hint: 'Tente voz calma e educada. Ex: "Tá bom... tudo certo por aqui... tô bem, obrigado." sem exageros.',
    tags: ['tranquilo', 'neutro', 'educado'],
    defaultPitch: 1.0,
    defaultRate: 0.9,
  },
  {
    e: '🙃',
    name: 'Irônico Sorridente',
    desc: 'Sorriso de cabeça pra baixo, irônico e passivo-agressivo',
    hint: 'Tente ironia fina com sorriso na voz. Ex: "Tá ótimo... adorei... que maravilha mesmo... hm." seco mas sorrindo.',
    tags: ['irônico', 'passivo-agressivo', 'sorridente'],
    defaultPitch: 1.0,
    defaultRate: 0.88,
  },
  {
    e: '😉',
    name: 'Piscadinha',
    desc: 'Piscando o olho, sugestivo e maroto',
    hint: 'Tente voz marota e sugestiva. Ex: "Entende o que tô dizendo... né? Fica esperto aí..." com cumplicidade.',
    tags: ['maroto', 'sugestivo', 'cúmplice'],
    defaultPitch: 1.05,
    defaultRate: 0.92,
  },
  {
    e: '😊',
    name: 'Envergonhada',
    desc: 'Sorrindo com bochechas rosadas, tímida',
    hint: 'Tente voz tímida e envergonhada. Ex: "Ai... que fofo... que coisa... fico até sem jeito, sério..." corada.',
    tags: ['tímido', 'envergonhado', 'fofo'],
    defaultPitch: 1.15,
    defaultRate: 0.88,
  },
  {
    e: '😇',
    name: 'Santinha',
    desc: 'Anjinho, inocente demais, muito santinha',
    hint: 'Tente voz angelical e super inocente. Ex: "Eu? Não fui eu não... juro! Sou inocente! Promessa!" angelical.',
    tags: ['inocente', 'angelical', 'santinha'],
    defaultPitch: 1.35,
    defaultRate: 0.95,
  },

  // ── AMOR E AFETO ──────────────────────────────────────
  {
    e: '😍',
    name: 'Apaixonadíssima',
    desc: 'Olhos de coração, completamente encantada',
    hint: 'Tente voz derretendo de admiração. Ex: "Meu Deus... que lindo... tô com os olhos brilhando de verdade..." suspirando.',
    tags: ['encantado', 'admiração', 'derretendo'],
    defaultPitch: 1.25,
    defaultRate: 0.88,
  },
  {
    e: '😘',
    name: 'Beijinho',
    desc: 'Mandando beijo, carinhosa',
    hint: 'Tente voz carinhosa mandando beijo. Ex: "Beijo meu amor! Saudades! Te mando um beijão daqui!" com carinho.',
    tags: ['carinhoso', 'beijo', 'afetuoso'],
    defaultPitch: 1.2,
    defaultRate: 0.9,
  },
  {
    e: '😗',
    name: 'Beijocas',
    desc: 'Boca em O, dando beijinhos',
    hint: 'Tente fazer barulho de beijo. Ex: "Mmuá! Mmuá! Beijo beijo beijo! Que saudade!" com muito carinho.',
    tags: ['beijo', 'carinhoso', 'fofo'],
    defaultPitch: 1.2,
    defaultRate: 0.95,
  },
  {
    e: '😚',
    name: 'Beijo Envergonhado',
    desc: 'Beijo com bochechas coradas, tímida',
    hint: 'Tente beijo tímido e envergonhado. Ex: "Ei... t-toma... um beijo... fica quieto tá..." todo corado.',
    tags: ['tímido', 'corado', 'beijo'],
    defaultPitch: 1.15,
    defaultRate: 0.85,
  },
  {
    e: '😙',
    name: 'Beijo Feliz',
    desc: 'Beijo com olhos sorridentes',
    hint: 'Tente beijo alegre e descontraído. Ex: "Mmuá! Que dia bom! Beijo em todo mundo! Tô feliz!" animado.',
    tags: ['alegre', 'beijo', 'descontraído'],
    defaultPitch: 1.2,
    defaultRate: 1.0,
  },

  // ── LÍNGUA E EXPRESSÕES ───────────────────────────────
  {
    e: '😛',
    name: 'Língua de Fora',
    desc: 'Mostrando a língua, travessa e irreverente',
    hint: 'Tente voz irreverente e travessa. Ex: "Bleeeeh! Nananana não vou fazer! Tô me lixando!" com deboche.',
    tags: ['travessa', 'irreverente', 'deboche'],
    defaultPitch: 1.3,
    defaultRate: 1.1,
  },
  {
    e: '😝',
    name: 'Olho Fechado Língua',
    desc: 'Olhos fechados mostrando língua, zuando',
    hint: 'Tente zoação exagerada. Ex: "BLAAAAAH! Zuei! Fui eu! Hahahah! Não me pega!" gozando da situação.',
    tags: ['zoação', 'engraçado', 'travessa'],
    defaultPitch: 1.4,
    defaultRate: 1.2,
  },
  {
    e: '😜',
    name: 'Piscando Língua',
    desc: 'Piscando e mostrando língua, loucona',
    hint: 'Tente voz loucona e divertida. Ex: "Eheheh tô louca! Que isso! Vai encarar?! Bora!" agitada e divertida.',
    tags: ['loucona', 'divertida', 'agitada'],
    defaultPitch: 1.35,
    defaultRate: 1.15,
  },
  {
    e: '🤪',
    name: 'Malucona',
    desc: 'Completamente maluca, caótica',
    hint: 'Tente loucura absoluta. Ex: "BLAAAAH AHAHAHA que isso!! Tô surta! Surta total! Aaaaah!" caótico.',
    tags: ['maluca', 'caótica', 'surta'],
    defaultPitch: 1.5,
    defaultRate: 1.35,
  },

  // ── PENSAMENTOS E EXPRESSÕES ──────────────────────────
  {
    e: '🤨',
    name: 'Desconfiada',
    desc: 'Sobrancelha levantada, desconfiada',
    hint: 'Tente voz desconfiada e questionadora. Ex: "Espera... isso não tá certo... você tem certeza disso mesmo?" séria.',
    tags: ['desconfiada', 'questionadora', 'séria'],
    defaultPitch: 0.95,
    defaultRate: 0.88,
  },
  {
    e: '😐',
    name: 'Inexpressiva',
    desc: 'Rosto neutro, sem expressão nenhuma',
    hint: 'Tente voz completamente monótona. Ex: "Ah. Tá. Ok. Certo. Entendi. Sim." sem nenhuma emoção.',
    tags: ['neutro', 'monótono', 'sem emoção'],
    defaultPitch: 1.0,
    defaultRate: 0.85,
  },
  {
    e: '😑',
    name: 'Entediada',
    desc: 'Olhos vazios, completamente entediada',
    hint: 'Tente tédio absoluto. Ex: "...que tédio... não aguento mais... quero ir embora... que saco." arrastado.',
    tags: ['entediado', 'vazio', 'saco'],
    defaultPitch: 0.88,
    defaultRate: 0.72,
  },
  {
    e: '🙄',
    name: 'Revirou os Olhos',
    desc: 'Revirando os olhos, exasperada',
    hint: 'Tente exasperação com revirada de olhos na voz. Ex: "Nossa... sério mesmo? De novo isso? Meu Deus..." bufando.',
    tags: ['exasperada', 'irritada', 'cansada'],
    defaultPitch: 0.95,
    defaultRate: 0.92,
  },
  {
    e: '😒',
    name: 'Desapontada',
    desc: 'Cara feia, sem graça, desapontada',
    hint: 'Tente decepção e desapontamento. Ex: "...não era isso que eu esperava. Tô desapontada, sério." fria.',
    tags: ['desapontada', 'fria', 'decepcionada'],
    defaultPitch: 0.9,
    defaultRate: 0.85,
  },

  // ── TRISTEZA E DOR ────────────────────────────────────
  {
    e: '😔',
    name: 'Pensativa Triste',
    desc: 'Pensativa e levemente triste, cabisbaixa',
    hint: 'Tente voz baixa e reflexiva triste. Ex: "Tô pensando aqui... não sei... tô um pouco pra baixo hoje..." devagar.',
    tags: ['triste', 'reflexiva', 'cabisbaixa'],
    defaultPitch: 0.88,
    defaultRate: 0.78,
  },
  {
    e: '😞',
    name: 'Desanimada',
    desc: 'Desanimada, decepcionada consigo',
    hint: 'Tente desânimo e decepção. Ex: "Não deu certo... de novo... que frustração... não acredito em mim." sem energia.',
    tags: ['desanimada', 'frustrada', 'decepcionada'],
    defaultPitch: 0.85,
    defaultRate: 0.75,
  },
  {
    e: '😟',
    name: 'Preocupada',
    desc: 'Preocupada, algo não está bem',
    hint: 'Tente preocupação genuína na voz. Ex: "Tô preocupada... não tá certo... e se der errado? E se...?" ansiosa.',
    tags: ['preocupada', 'ansiosa', 'tensa'],
    defaultPitch: 1.0,
    defaultRate: 1.05,
  },
  {
    e: '😢',
    name: 'Chorando Baixinho',
    desc: 'Uma lágrima caindo, tristeza contida',
    hint: 'Tente tristeza contida, segurando o choro. Ex: "Não... tô bem... é só uma lágrima... descuida..." voz embargada.',
    tags: ['triste', 'contido', 'lágrima'],
    defaultPitch: 0.9,
    defaultRate: 0.8,
  },
  {
    e: '😓',
    name: 'Suada de Estresse',
    desc: 'Estressada, suando frio, sobrecarregada',
    hint: 'Tente estresse e sobrecarga. Ex: "Meu Deus... não consigo... tem tanto pra fazer... não aguento mais..." sufocada.',
    tags: ['estressada', 'sobrecarregada', 'sufocada'],
    defaultPitch: 1.0,
    defaultRate: 1.1,
  },

  // ── MEDO E SURPRESA ───────────────────────────────────
  {
    e: '😨',
    name: 'Assustada',
    desc: 'Com medo, assustada, olhos arregalados',
    hint: 'Tente medo genuíno na voz. Ex: "Que... que foi isso?! Que barulho! Tô com medo... sério..." tremendo.',
    tags: ['medo', 'assustada', 'tremendo'],
    defaultPitch: 1.3,
    defaultRate: 1.2,
  },
  {
    e: '😰',
    name: 'Suando de Medo',
    desc: 'Suando frio de nervoso, apavorada',
    hint: 'Tente terror contido. Ex: "Tô... tô tremendo... que situação... não consigo nem falar direito..." gaguejando.',
    tags: ['apavorada', 'nervosa', 'tremendo'],
    defaultPitch: 1.2,
    defaultRate: 1.15,
  },
  {
    e: '😮',
    name: 'Boquiaberta',
    desc: 'Boca aberta de surpresa, chocada',
    hint: 'Tente surpresa total, boca aberta. Ex: "Não... não acredito... que? Isso aconteceu de verdade?" perplexa.',
    tags: ['surpresa', 'perplexa', 'chocada'],
    defaultPitch: 1.2,
    defaultRate: 1.1,
  },
  {
    e: '😯',
    name: 'Emudecida',
    desc: 'Sem palavras, completamente emudecida',
    hint: 'Tente ficar sem palavras. Ex: "Eu... eu... não... não sei o que dizer... que... nossa." gaguejando de surpresa.',
    tags: ['emudecida', 'sem palavras', 'perplexa'],
    defaultPitch: 1.1,
    defaultRate: 0.9,
  },
  {
    e: '😲',
    name: 'Chocadíssima',
    desc: 'Choque total, completamente incrédula',
    hint: 'Tente choque absoluto. Ex: "QUE?! NÃO! ISSO NÃO É REAL! Você tá brincando comigo?!" esbugalhada.',
    tags: ['choque', 'incrédula', 'esbugalhada'],
    defaultPitch: 1.4,
    defaultRate: 1.3,
  },

  // ── RAIVA E FRUSTRAÇÃO ────────────────────────────────
  {
    e: '😠',
    name: 'Brava',
    desc: 'Brava, irritada, sobrancelha franzida',
    hint: 'Tente raiva firme e controlada. Ex: "Tô brava. Muito brava. Não tô gostando nada disso, tá?" séria e firme.',
    tags: ['brava', 'firme', 'irritada'],
    defaultPitch: 0.88,
    defaultRate: 1.0,
  },
  {
    e: '🤬',
    name: 'Xingando',
    desc: 'Xingando com símbolos, fúria máxima',
    hint: 'Tente fúria absoluta. Ex: "@#$%! Que situação! Não aguento! Tô fora de mim! @#$%!" explodindo de raiva.',
    tags: ['fúria', 'explosiva', 'xingando'],
    defaultPitch: 0.8,
    defaultRate: 1.3,
  },
  {
    e: '🤒',
    name: 'Doentinha',
    desc: 'Doente, com febre, voz nasalada',
    hint: 'Tente voz nasalada de resfriado. Ex: "Ai... tô doente... com febre... que mal estar... minha cabeça..." rouca.',
    tags: ['doente', 'nasalada', 'mal estar'],
    defaultPitch: 0.85,
    defaultRate: 0.75,
  },
  {
    e: '🤕',
    name: 'Machucada',
    desc: 'Machucada, com curativo, sofrendo',
    hint: 'Tente dor contida. Ex: "Ai... tô machucada... dói aqui ó... vai devagar, ai ai ai..." gemendo de dor.',
    tags: ['machucada', 'dor', 'sofrendo'],
    defaultPitch: 0.88,
    defaultRate: 0.78,
  },
  {
    e: '🤢',
    name: 'Enjoada',
    desc: 'Enjoada, com náusea, passando mal',
    hint: 'Tente enjoo e náusea na voz. Ex: "Ui... tô enjoada... não me fala de comida... ai que enjôo..." fraca.',
    tags: ['enjoada', 'náusea', 'passando mal'],
    defaultPitch: 0.9,
    defaultRate: 0.8,
  },
  {
    e: '🤮',
    name: 'Nojenta',
    desc: 'Vomitando de nojo, asco total',
    hint: 'Tente nojo e asco absoluto. Ex: "BLEGH! Que nojo! Que coisa horrível! Não aguento! BLARGH!" com asco.',
    tags: ['nojo', 'asco', 'horrível'],
    defaultPitch: 0.95,
    defaultRate: 1.1,
  },
  {
    e: '🤧',
    name: 'Espirrentinha',
    desc: 'Espirros e nariz escorrendo, gripada',
    hint: 'Tente voz gripada com espirros. Ex: "Atchim! Ai desculpa... atchim! Tô toda gripada... atchim!" nasalada.',
    tags: ['gripada', 'espirro', 'nasalada'],
    defaultPitch: 0.88,
    defaultRate: 0.9,
  },
  {
    e: '🥵',
    name: 'Com Calor',
    desc: 'Com muito calor, suando, ofegante',
    hint: 'Tente calor intenso e ofegante. Ex: "Meu Deus que calor... tô derretendo... alguém tem água? Haff haff..." ofegante.',
    tags: ['calor', 'ofegante', 'suando'],
    defaultPitch: 1.0,
    defaultRate: 0.85,
  },
  {
    e: '🥶',
    name: 'Com Frio',
    desc: 'Com muito frio, tremendo, gelada',
    hint: 'Tente voz tremendo de frio. Ex: "Q-q-que frio... tô t-t-tremendo... alguém tem um c-c-cobertor?" dentes batendo.',
    tags: ['frio', 'tremendo', 'gelada'],
    defaultPitch: 1.05,
    defaultRate: 0.88,
  },

  // ── ATITUDES ──────────────────────────────────────────
  {
    e: '🤓',
    name: 'Nerd',
    desc: 'Nerd entusiasmada, explicando tudo',
    hint: 'Tente voz nerd animada. Ex: "Na verdade, tecnicamente falando, se você analisar os dados... é muito interessante!" animada.',
    tags: ['nerd', 'intelectual', 'entusiasmada'],
    defaultPitch: 1.1,
    defaultRate: 1.15,
  },
  {
    e: '🥸',
    name: 'Disfarçada',
    desc: 'Com disfarce, fingindo ser outra pessoa',
    hint: 'Tente voz disfarçada e suspeita. Ex: "Olá... eu sou totalmente uma pessoa normal... nada a ver aqui..." sussurrando.',
    tags: ['disfarçada', 'suspeita', 'fingindo'],
    defaultPitch: 0.92,
    defaultRate: 0.88,
  },
  {
    e: '🤑',
    name: 'Sovina',
    desc: 'Olhos de cifrão, obcecada com dinheiro',
    hint: 'Tente voz obcecada com dinheiro. Ex: "DINHEIRO! Lucro! Mais! Quero mais! Quanto vai render?! $$$" ganancioso.',
    tags: ['dinheiro', 'gananciosa', 'obcecada'],
    defaultPitch: 1.2,
    defaultRate: 1.2,
  },
  {
    e: '😶',
    name: 'Sem Palavras',
    desc: 'Sem boca, completamente muda',
    hint: 'Tente silêncio constrangedor. Ex: "..." apenas sons vagos, sem palavras de verdade, murmúrios sem sentido.',
    tags: ['muda', 'silêncio', 'constrangida'],
    defaultPitch: 1.0,
    defaultRate: 0.7,
  },
  {
    e: '🫠',
    name: 'Derretendo',
    desc: 'Derretendo de vergonha ou calor',
    hint: 'Tente voz derretendo lentamente. Ex: "Tô... tô derretendo... que vergonha... some comigo... derretendo..." lento.',
    tags: ['vergonha', 'derretendo', 'lento'],
    defaultPitch: 0.85,
    defaultRate: 0.65,
  },
  {
    e: '🫥',
    name: 'Invisível',
    desc: 'Pontilhada, querendo ser invisível',
    hint: 'Tente voz quase inaudível. Ex: "Psiu... sou eu... pode me ignorar... só tô aqui... sem me ver..." sussurrando.',
    tags: ['invisível', 'sussurro', 'tímida'],
    defaultPitch: 1.1,
    defaultRate: 0.75,
  },

  // ── GESTOS ────────────────────────────────────────────
  {
    e: '🫡',
    name: 'Sentido',
    desc: 'Na posição sentido, respeitosa',
    hint: 'Tente voz firme e respeitosa. Ex: "Sim senhor! Pode deixar! Missão cumprida! A postos!" com postura.',
    tags: ['firme', 'respeitosa', 'postura'],
    defaultPitch: 0.95,
    defaultRate: 1.0,
  },
  {
    e: '🤭',
    name: 'Bocão Tapado',
    desc: 'Mão na boca, surpresa ou rindo escondido',
    hint: 'Tente riso abafado com a mão. Ex: "Pfff... ahahah... não posso falar... pfff que situação!" rindo escondido.',
    tags: ['rindo escondido', 'surpresa', 'abafado'],
    defaultPitch: 1.2,
    defaultRate: 1.0,
  },
  {
    e: '🤫',
    name: 'Segredo',
    desc: 'Pedindo silêncio, guardando segredo',
    hint: 'Tente sussurro de segredo. Ex: "Psiu... vem cá... não conta pra ninguém... é segredo nosso... psiu!" sussurrando.',
    tags: ['segredo', 'sussurro', 'cúmplice'],
    defaultPitch: 1.0,
    defaultRate: 0.8,
  },
  {
    e: '🫢',
    name: 'Ops!',
    desc: 'Mão na boca de susto, ops!',
    hint: 'Tente susto de ter falado algo errado. Ex: "Ops! Eu disse isso em voz alta? Não era pra falar... desculpa!" arrependida.',
    tags: ['ops', 'susto', 'arrependida'],
    defaultPitch: 1.2,
    defaultRate: 1.1,
  },
  {
    e: '🧐',
    name: 'Investigadora',
    desc: 'Com monóculo, investigando tudo',
    hint: 'Tente voz investigativa e analítica. Ex: "Hmm... interessante... deixa eu analisar... tem algo suspeito aqui..." séria.',
    tags: ['investigadora', 'analítica', 'séria'],
    defaultPitch: 0.95,
    defaultRate: 0.85,
  },
  {
    e: '🥱',
    name: 'Bocejando',
    desc: 'Bocejo gigante, extremamente entediada',
    hint: 'Tente o bocejo mais longo da sua vida. Ex: "Aaaaaahhmmm... que tédio... tô morrendo de sono... aaaahmmm..." arrastado.',
    tags: ['bocejo', 'entediada', 'sono'],
    defaultPitch: 0.82,
    defaultRate: 0.62,
  },

  // ── CARINHAS ESPECIAIS ────────────────────────────────
  {
    e: '😈',
    name: 'Diabinha',
    desc: 'Sorrindo com chifres, fazendo maldade',
    hint: 'Tente voz diabólica e travessa. Ex: "Eheheheheh... meu plano funcionou... ninguém vai saber que fui eu... heheheh!" mal.',
    tags: ['diabólica', 'malvada', 'travessa'],
    defaultPitch: 0.85,
    defaultRate: 0.95,
  },
  {
    e: '👿',
    name: 'Furiosa Diabinha',
    desc: 'Chifres com raiva, diabólica furiosa',
    hint: 'Tente raiva diabólica. Ex: "NINGUÉM ME PARA! Vou destruir tudo! Ahahaha! Meu plano é perfeito!" maléfica.',
    tags: ['diabólica', 'furiosa', 'maléfica'],
    defaultPitch: 0.78,
    defaultRate: 1.1,
  },
  {
    e: '💀',
    name: 'Morta de Rir',
    desc: 'Caveira, morta de rir ou literalmente morta',
    hint: 'Tente "morrer" de rir ou dramaticamente. Ex: "Tô MORTA! Morrendo! Já virei caveira de tanto rir! Ahahaha!" ou dramático.',
    tags: ['morta', 'caveira', 'dramática'],
    defaultPitch: 0.82,
    defaultRate: 1.0,
  },
  {
    e: '🤡',
    name: 'Palhaça',
    desc: 'Palhaça, engraçada e assustadora',
    hint: 'Tente voz de palhaço exagerada. Ex: "HONK HONK! Boa tarde! Que tal uma piada?! HONK HONK!" exagerado e palhaço.',
    tags: ['palhaço', 'exagerada', 'honk'],
    defaultPitch: 1.3,
    defaultRate: 1.0,
  },
  {
    e: '👻',
    name: 'Fantasminha',
    desc: 'Fantasma assustando ou sendo fofo',
    hint: 'Tente voz de fantasma. Ex: "BUUuuuu... sou o fantasma que você pediu... buuuuu... tem medo? Buuuu!" assombrando.',
    tags: ['fantasma', 'buu', 'assombrando'],
    defaultPitch: 0.88,
    defaultRate: 0.82,
  },
  {
    e: '👾',
    name: 'Alienígena',
    desc: 'Monstro de videogame, vindo do espaço',
    hint: 'Tente voz robótica de videogame. Ex: "BLEEP BLOOP... sou do espaço... vim em missão... BLEEP BLOOP..." robótico.',
    tags: ['robótico', 'alienígena', 'videogame'],
    defaultPitch: 1.4,
    defaultRate: 0.95,
  },
  {
    e: '🤖',
    name: 'Robô',
    desc: 'Robô, voz mecânica e computadorizada',
    hint: 'Tente voz de robô mecânica. Ex: "OLÁ-HU-MA-NO. EU-SOU-UM-RO-BÔ. POR-FA-VOR-OBE-DE-ÇA." bem travado.',
    tags: ['robô', 'mecânico', 'computador'],
    defaultPitch: 0.9,
    defaultRate: 0.82,
  },
];
