/**
 * data.js — EmojiDub
 * Banco de dados de emojis com personalidades e dicas de dublagem
 */

const EMOJI_DATA = [
  {
    e: '😂',
    name: 'Gargalhada',
    desc: 'Rir sem parar, histérico, não consegue parar',
    hint: 'Tente uma risada escandalosa e contagiante. Ex: "Hahahaha meu Deus não aguento!" ou apenas uma risada pura e incontrolável.',
    tags: ['risada', 'contagiante', 'explosivo'],
    defaultPitch: 1.4,
    defaultRate: 1.3,
  },
  {
    e: '😭',
    name: 'Choro Dramático',
    desc: 'Choro exagerado, teatral, muito dramático',
    hint: 'Tente um choro bem dramático e sofrido. Ex: "Aiiiii que tristeza... não aguento mais..." ou simplesmente chore com intensidade.',
    tags: ['triste', 'dramático', 'exagerado'],
    defaultPitch: 0.9,
    defaultRate: 0.85,
  },
  {
    e: '😡',
    name: 'Furiosa',
    desc: 'Raiva pura, bufando e resmungando',
    hint: 'Tente um resmungo irritado e bufante. Ex: "Não acredito! Que absurdo isso!" com muita raiva na voz.',
    tags: ['raiva', 'intenso', 'bufante'],
    defaultPitch: 0.85,
    defaultRate: 1.2,
  },
  {
    e: '😴',
    name: 'Sonâmbulo',
    desc: 'Bocejando, arrastado, quase dormindo',
    hint: 'Tente um bocejo longo e arrastado. Ex: "Ahmmm... tô dormindo... que sono..." bem devagarzinho e sem energia.',
    tags: ['sono', 'arrastado', 'bocejo'],
    defaultPitch: 0.8,
    defaultRate: 0.6,
  },
  {
    e: '🤩',
    name: 'Maravilhado',
    desc: 'Empolgação extrema, animadíssimo',
    hint: 'Tente empolgação máxima! Ex: "NOSSA QUE INCRÍVEL! Que coisa linda! Amei!!!" com muita energia e entusiasmo.',
    tags: ['animado', 'vibrante', 'empolgado'],
    defaultPitch: 1.5,
    defaultRate: 1.4,
  },
  {
    e: '🥺',
    name: 'Carente',
    desc: 'Voz pequena, fofa e suplicante',
    hint: 'Tente voz pequenininha e carente. Ex: "Por faaavorr... você consegue? Por favorzinhoo?" bem fininho e suplicante.',
    tags: ['fofo', 'suplicante', 'delicado'],
    defaultPitch: 1.3,
    defaultRate: 0.9,
  },
  {
    e: '😱',
    name: 'Apavorada',
    desc: 'Horror puro, chocado e assustado',
    hint: 'Tente um grito de susto contido. Ex: "Não! Que!? Meu Deus! Não acredito!" com voz horrorizada.',
    tags: ['assustado', 'chocado', 'intenso'],
    defaultPitch: 1.4,
    defaultRate: 1.3,
  },
  {
    e: '🤣',
    name: 'Histérica',
    desc: 'Rindo rolando no chão, completamente histérica',
    hint: 'Tente riso histérico incontrolável. Ex: "Ahahaha tô MORTA! Tô caindo! AHahahaha socorro!" perdendo o fôlego.',
    tags: ['histérico', 'caótico', 'rolando'],
    defaultPitch: 1.6,
    defaultRate: 1.5,
  },
  {
    e: '😏',
    name: 'Debochado',
    desc: 'Tom irônico, arrogante e debochado',
    hint: 'Tente um "hmm" irônico e lento. Ex: "Ah claro... com certeza... se você achar..." bem debochado e pausado.',
    tags: ['irônico', 'debochado', 'arrogante'],
    defaultPitch: 1.0,
    defaultRate: 0.85,
  },
  {
    e: '🥰',
    name: 'Apaixonada',
    desc: 'Derretendo de amor, completamente apaixonada',
    hint: 'Tente voz melosa e apaixonada. Ex: "Ai que amor... que coisa linda... te amo tanto..." com suspiros suaves.',
    tags: ['amoroso', 'suave', 'derretendo'],
    defaultPitch: 1.2,
    defaultRate: 0.85,
  },
  {
    e: '😤',
    name: 'Indignado',
    desc: 'Bufando de indignação, muito ofendido',
    hint: 'Tente um bufar indignado. Ex: "Humpf! Que descaso! Sério?! Que falta de respeito!" bufando forte entre as frases.',
    tags: ['indignado', 'bufante', 'ofendido'],
    defaultPitch: 0.9,
    defaultRate: 1.1,
  },
  {
    e: '🤔',
    name: 'Pensativo',
    desc: 'Hmm… pensando alto, reflexivo',
    hint: 'Tente pensar em voz alta devagar. Ex: "Hmm... interessante... deixa eu pensar... hm... sim..." bem pausado e reflexivo.',
    tags: ['reflexivo', 'pensativo', 'lento'],
    defaultPitch: 0.95,
    defaultRate: 0.8,
  },
  {
    e: '🎉',
    name: 'Festeiro',
    desc: 'Eufórico de festa, animadíssimo',
    hint: 'Tente grito de festa máximo! Ex: "VAMOS! É FESTA! Que animação! UHUU! YEAAH!" como se estivesse pulando de alegria.',
    tags: ['festeiro', 'eufórico', 'explosivo'],
    defaultPitch: 1.5,
    defaultRate: 1.4,
  },
  {
    e: '😎',
    name: 'Coolzão',
    desc: 'Confiante, cool, pausado e estiloso',
    hint: 'Tente falar super pausado e confiante. Ex: "Relaxa. Tô aqui. Pode contar comigo. Sempre foi assim." sem pressa alguma.',
    tags: ['cool', 'confiante', 'estiloso'],
    defaultPitch: 0.85,
    defaultRate: 0.8,
  },
  {
    e: '🤯',
    name: 'Mente Explodida',
    desc: 'Incrédulo, confuso, cabeça explodindo',
    hint: 'Tente incredulidade total. Ex: "MAS COMO?! Espera! Que!? Não entendo nada! Minha cabeça!" de forma caótica e confusa.',
    tags: ['caótico', 'incrédulo', 'confuso'],
    defaultPitch: 1.3,
    defaultRate: 1.3,
  },
  {
    e: '😫',
    name: 'Exausta',
    desc: 'Completamente esgotada, sem energia',
    hint: 'Tente esgotamento total. Ex: "Ai... não aguento mais... tô destruída... sem energia alguma..." bem lento e sem força.',
    tags: ['esgotado', 'sem energia', 'lento'],
    defaultPitch: 0.85,
    defaultRate: 0.65,
  },
  {
    e: '🤗',
    name: 'Calorosa',
    desc: 'Abraçando com a voz, acolhedora',
    hint: 'Tente voz calorosa e acolhedora. Ex: "Que bom te ver! Vem cá! Você é incrível, sabia? Te adoro muito!" com muito calor humano.',
    tags: ['caloroso', 'acolhedor', 'suave'],
    defaultPitch: 1.1,
    defaultRate: 0.95,
  },
  {
    e: '😬',
    name: 'Constrangido',
    desc: 'Awkward, constrangido, situação estranha',
    hint: 'Tente um riso nervoso e constrangido. Ex: "Heh... é... isso... que situação né... heheh..." completamente sem graça.',
    tags: ['awkward', 'nervoso', 'constrangido'],
    defaultPitch: 1.0,
    defaultRate: 1.0,
  },
  {
    e: '🥹',
    name: 'Emocionada',
    desc: 'Segurando o choro de tanto amor',
    hint: 'Tente voz embargada de emoção. Ex: "Não... que coisa mais linda... tô quase chorando... de verdade..." tremendo de emoção.',
    tags: ['emocionado', 'tocado', 'sensível'],
    defaultPitch: 1.1,
    defaultRate: 0.85,
  },
  {
    e: '😆',
    name: 'Alegre',
    desc: 'Feliz e risonho, sem parar de sorrir',
    hint: 'Tente voz animada e risonha. Ex: "Que delícia! Que dia incrível! Tô muito feliz hoje, sério!" com sorriso na voz.',
    tags: ['feliz', 'alegre', 'animado'],
    defaultPitch: 1.2,
    defaultRate: 1.1,
  },
];
